GET http://localhost:3000/

###

GET http://localhost:3000/survey

###

POST http://localhost:3000/survey/9314
Content-Type: application/json

{
   "kdks":"akalsd",
   "asj":"slkdasldkl",
   "questions":["Hello","Malav","Shah","Demo","Follow"]
}
